version: "3"

services:
  node1:
    build:
      context: nodes
      args:
        SERVER_ID: 10
    volumes:
      - node1_db:/var/lib/mysql
    env_file:
      - ./env/nodes.env
    networks:
      - mysql-cluster

  node2:
    build:
      context: nodes
      args:
        SERVER_ID: 20
    volumes:
      - node2_db:/var/lib/mysql
    env_file:
      - ./env/nodes.env
    networks:
      - mysql-cluster

  node3:
    build:
      context: nodes
      args:
        SERVER_ID: 30
    image: mysql/mysql-server
    volumes:
      - node3_db:/var/lib/mysql
    env_file:
      - ./env/nodes.env
    networks:
      - mysql-cluster

  router:
    image: mysql/mysql-router
    ports:
      - 6446:6446
    env_file:
      - ./env/router.env
    networks:
     - mysql-cluster


networks:
  mysql-cluster:

volumes:
  node1_db:
  node2_db:
  node3_db:
